Detect the availability of fstat.f_iosize.
This structure member is not available on Linux, but can be found on
BSDs and OS X.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -207,6 +207,22 @@ fi
 rm -f fake_strlcat*
 
 
+# Check if we have statfs.f_iosize
+echo -n "statfs.f_iosize... "
+cat <<EOF > fake_statfs_f_iosize.c
+#include <sys/stat.h>
+#include <sys/statfs.h>
+main() { struct statfs fsb; int x = fsb.f_iosize; }
+EOF
+if ! ${CC} fake_statfs_f_iosize.c -o /dev/null 1>/dev/null 2>/dev/null; then
+	echo "not found (we'll use a default buffer size)"
+	CFLAGS="$CFLAGS -DHAS_NO_F_IOSIZE"
+else
+	echo yes
+fi
+rm -f fake_statfs_f_iosize*
+
+
 # Check if we have wcslcpy
 echo -n "wcslcpy... "
 cat <<EOF > fake_wcslcpy.c
